{
 "title": "ZenithPlanner",
 "description": "Keep track of the location data saved in ZenithPlanner.",
 "tags": [ "zenithplanner" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Total Vacation Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM schedule_entries WHERE $__timeFilter(date) AND status = 'Vacation'"
    }
   ]
  },
  {
   "title": "Total Study Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM schedule_entries WHERE $__timeFilter(date) AND status != 'Vacation' AND location_code != 'W';"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT status, date\nFROM schedule_entries\nWHERE $__timeFilter(date)"
    }
   ]
  },
  {
   "title": "Location Distribution",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status, count(date) AS days\nFROM schedule_entries\nWHERE\n  $__timeFilter(date) AND\n  location_code != 'W'\nGROUP BY status\nORDER BY days DESC"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT status, count(date) AS days\nFROM schedule_entries\nWHERE\n  $__timeFilter(date) AND\n  location_code != 'W'\nGROUP BY status\nORDER BY days DESC"
    }
   ]
  }
 ]
}